In [2]:
import numpy as np 
import time 

In [3]:
arr = np.array([1,2,3,4,5])
print(arr , type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
#Numpy vs Lists

#Time calculation

size = 10_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time = {end - start} seconds")

np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2
end = time.time()
print(f"Numpy array time = {end - start} seconds")

Python list time = 0.7743980884552002 seconds
Numpy array time = 0.018848180770874023 seconds


In [5]:
#Memory
import sys
print(f"size of python lists is {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"size of numpy array is {np_array.nbytes} bytes")

size of python lists is 800000560000000 bytes
size of numpy array is 80000000 bytes


In [7]:
#Creating Numpy arrays
#From Lists
arr = np.array([1,2,3,4,5])
print(arr , arr.shape)

#2D Array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2 , arr2.shape)

[1 2 3 4 5] (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [20]:
#creating from scratch
arr1 = np.zeros((2,3), dtype="int64") #prefill with zero
print(arr1)

arr2 = np.ones((5,)) #prefill with one
print(arr2)

arr3 = np.full((3,4), 34) #prefill with value 
print(arr3)

arr4 = np.eye(3) #identity matrix 
print(arr4)

arr5 = np.arange(1,11) #range(start,end,step)
print(arr5)

arr6 = np.linspace(1,100,8) #evenly spaced arrays
print(arr6)

[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[34 34 34 34]
 [34 34 34 34]
 [34 34 34 34]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[  1.          15.14285714  29.28571429  43.42857143  57.57142857
  71.71428571  85.85714286 100.        ]


In [25]:
#Properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) #dimensions = m * n
print(arr.size) # total elements
print(arr.dtype)
print(arr.ndim) #no of dimensions

#type casting
float_arr = arr.astype(np.float64)
print(float_arr)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [28]:
#Operations

#reshape
arr = np.array([[1,2,3],[4,5,6]])
print(arr , arr.shape)

reshape = arr.reshape((3,2))
print(reshape, reshape.shape)

flattened = arr.flatten() # 2D->1D
print(flattened)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [36]:
#indexing
arr = np.array([12,2,4,5,6])
print(arr[2])

#fancy indexing
arr2 = np.array([1,2,3,4,5,6,7,8,9])
idx = [0,1,3]
print(arr2[idx])

#Boolean indexing
print(arr2[arr2%2==0])

#slicing [start:end:step]
print(arr2[0:4])
 

4
[1 2 4]
[2 4 6 8]
[1 2 3 4]
